// Class automatically generated by Dev-C++ New Class wizard

#include "abrir_fichero.h" // class's header file


// class constructor
abrir_fichero::abrir_fichero()
{
	// insert your code here
	objTraza = new traza();
	objTraza->print("abrir_fichero::abrir_fichero()");
	this->Settexto(NULL);
}

// class destructor
abrir_fichero::~abrir_fichero()
{
	// insert your code here
    if (this->Gettexto() != NULL)
    {
        delete [] this->texto;
    }
}


// No description
bool abrir_fichero::procesar_fichero(char *filename)
{
    FILE* fin;
    long tam = 0;
    objTraza->print("abrir_fichero::procesar_fichero(char *filename)");


	if (this->Gettexto() != NULL)
	    delete [] texto;

	if ((fin = fopen(filename,"rb"))==NULL)
	{
        objTraza->print("abrir_fichero::procesar_fichero, error al procesar el fichero");
        //fclose(fin);
        return false;
    }
    else
    {
        tam = this->getSize(fin);
        objTraza->print("abrir_fichero::procesar_fichero, leemos el fichero de tam",tam);
        this->texto = new char[tam+1];
        memset(this->texto, 0, tam+1);
        fread(this->texto, 1, tam, fin);
        fclose(fin);
        return true;
    }
}

bool abrir_fichero::crearTexto(char *datos)
{
    long tam = 0;

	if (this->Gettexto() != NULL)
	    delete [] texto;

    if (datos != NULL)
    {
        tam = strlen(datos);
        this->texto = new char[tam+1];
        memset(this->texto, '\0', tam+1);
        strcpy(this->texto,datos);
        return true;
    }
    return false;
}


long abrir_fichero::getSize(FILE *fin)
{
    long tam = 0;
    int curr_pos = ftell(fin);
    if (fin != NULL)
    {
         fseek(fin,0,SEEK_END);
         //tam = ftell(fin) - 1;
         tam = ftell(fin);
         fseek(fin,curr_pos*sizeof(char),SEEK_SET);
    }
//    printf("tam: %d\n",tam);
    return tam;


}

// returns the value of texto
char * abrir_fichero::Gettexto()
{
	return texto;
}


// sets the value of texto
void abrir_fichero::Settexto(char * x)
{
	texto = x;
}
void abrir_fichero::Settexto(char x, int i)
{
	texto[i] = x;
}



