// Class automatically generated by Dev-C++ New Class wizard

#ifndef ABRIR_FICHERO_H
#define ABRIR_FICHERO_H

#include <string.h>
#include <stdio.h>
#include "traza.h"


/*
 * No description
 */
class abrir_fichero
{
	public:
		// class constructor
		abrir_fichero();
		// class destructor
		~abrir_fichero();
		bool procesar_fichero(char *filename);
		long getSize(FILE *fin);
		void Settexto(char * x); // sets the value of texto
		char * Gettexto(); // returns the value of texto
//		void buscar_paginas(void);
		void Settexto(char x, int i);
		bool crearTexto(char *);

	protected:
        char * texto;
        traza *objTraza;

};

#endif // ABRIR_FICHERO_H
