// Class automatically generated by Dev-C++ New Class wizard

#ifndef MENUDATA_H
#define MENUDATA_H

#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <math.h>
#include <string.h>

class TMenuData
{
	public:

        TMenuData();
        ~TMenuData();

        struct my_struct_campo {
          char nombre[255];
          char props[4]; //d=directorio, f=fichero, s=reservado para otros botones: volver,...
        };

        struct my_struct_menu {
            my_struct_campo *campo;
            int numCampos;
            bool tieneProps;
            char nombreMenu[20];
        }*menus;

        void AddMenu(char *varNombre);
        void AddCampoMenu(int varMenu, char *varNombre, char *props);
        void AddCampoMenu(char *varNombre, char *props);
        void AddPropMenu(int varMenu, int varCampo, char *varNombre);
        void ModCampoMenu(int varMenu, int varCampo, char *varNombre, char *props);
        void clearCamposMenu(int varMenu);


        int posCampo;
        int posMenu;
        int posAntCampo;
        int posMenuScreenIni;
        int posMenuScreenFin;
        int numMenus;

        struct my_struct_mensajes {
          char textoMensaje[255];
        };

        struct my_struct_n_mensajes {
          my_struct_mensajes mensajes[8];
          int menus;
        }mensajes_menus;
};

#endif // MENU_H
