// Class automatically generated by Dev-C++ New Class wizard

#ifndef MENU_H
#define MENU_H

#include <SDL/SDL_ttf.h>
#include "pantalla.h" // inheriting class's header file
#include <SDL/SDL.h>
#include "image.h"

/*
 * No description
 */
class TMenu : public TPantalla
{
	public:
		// class constructor
		TMenu(SDL_Surface* screen);
		// class destructor
		~TMenu();
//		void MostrarExplorador(TText *visorTexto);
		// No description
		void anteriorCampo();
		// No description
		void siguienteCampo();
        void siguientePaginaCampo();
        void anteriorPaginaCampo();
        bool visible;
        void MostrarMenu(int numMenu);
  		void sangrado(int numMenu);
		TMenuData *menusD;
		void ResetMenus();
        void setTiempoLectura(int timer);
        int getTiempoLectura();
        void verTiempoLectura ();
        TImagen *miImagen;
        void IconosMenu(int var_numMenu, int var_posCampo, int var_topCampo);
        void reset_marcador();

	protected:

        int separacion;
        int top, left;
        void iniciarMensajesMenus();
        int tiempoInicioLectura;
        int tiempoLectura;
        TConfig *fichLang;


		char nombreFicheroAbierto[255];




};

#endif // MENU_H
