// Class automatically generated by Dev-C++ New Class wizard
#include "sound.h" // class's header file

// class constructor
TSound::TSound()
{
    //music = NULL;
    //Mix_FreeMusic(music);
    arrayMusic.numMusic = 0;
    cargar();
    printf("Cargamos Sound\n");
    SActivo = true;
}

TSound::~TSound()
{
    freeMusic();
}

void TSound::setSound(bool activo)
{
    SActivo = activo;
}

void TSound::cargar()
{
    arrayMusic.numMusic = 4;
    freeMusic();
    #ifdef GP2X
    arrayMusic.Music[0] = Mix_LoadMUS("sound/click.mp3");
    arrayMusic.Music[1] = Mix_LoadMUS("sound/volver.mp3");
    arrayMusic.Music[2] = Mix_LoadMUS("sound/clickMet.mp3");
    arrayMusic.Music[3] = Mix_LoadMUS("sound/pagina.mp3");
    #else
    arrayMusic.Music[0] = Mix_LoadMUS("sound\\click.mp3");
    arrayMusic.Music[1] = Mix_LoadMUS("sound\\volver.mp3");
    arrayMusic.Music[2] = Mix_LoadMUS("sound\\clickMet.mp3");
    arrayMusic.Music[3] = Mix_LoadMUS("sound\\pagina.mp3");
    #endif
}

void TSound::freeMusic()
{
    for (int i=0;i<arrayMusic.numMusic;i++)
    {
        arrayMusic.Music[i] = NULL;
        Mix_FreeMusic(arrayMusic.Music[i]);
    }
}


void TSound::play(int numMusic)
{
    //music = Mix_LoadMUS("sound\\click2.mp3");
	if (SActivo && numMusic < arrayMusic.numMusic && numMusic >= 0)
	if (Mix_PlayMusic(arrayMusic.Music[numMusic], 1) == -1)
	{
	    printf("Error al reproducir la musica\n");
	}
	else
	{
        //Mix_RewindMusic();
        //Mix_VolumeMusic(100);
        //Mix_PlayMusic(music, 1);
        //Mix_ResumeMusic();
        //Mix_HaltMusic();
        //music = NULL;
        //Mix_FreeMusic(music);
	}
}
