// Class automatically generated by Dev-C++ New Class wizard

#ifndef TDiccionario_H
#define TDiccionario_H

#include "tclist.h"
#include "abrir_fichero.h"
#include "tcstring.h"
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <math.h>

#include <string.h>


class TDiccionario : public abrir_fichero
{
	public:
		TDiccionario(char *);
		~TDiccionario();
		int find(char *);
		char * get();
		int findAprox(char *dato,TClist *datosSalida);


    private:
        char filename[255];
        char fileIndex[255];
        int *offsetLineasIndex;
        TClist *stringLineasIndex;
        int numLineasIndex;
        int cargarIndex();
        void guardarOrden (TClist *lista);
        bool procesar_linea_fichero(int);
        void formatear();
        void stringTrim(char *dato);
        TCString *string;
        traza *objTraza;


};


#endif // TImagen_H
