// Class automatically generated by Dev-C++ New Class wizard

#ifndef TRAZA_H
#define TRAZA_H

#include <stdio.h>
#include <string.h>
#include <time.h>
#include <string>


/*
 * Clase para generar trazas
 */
class traza
{
	public:
		// class constructor
		traza(char *ruta);
		traza();

		// class destructor
		~traza();

  	     void print(char *msg); //Pinta el mensaje en la traza
		 void print(char *msg,char *msg2);
		 void print(char *msg,int msg2);
		 void setTraza(bool estado);

    private:
  	     FILE* fout;
  	     char ruta[256];
  	     bool pintarTrazas;
};

#endif // TRAZA_H
