// Class automatically generated by Dev-C++ New Class wizard

#ifndef TTECLADOPANTALLA_H
#define TTECLADOPANTALLA_H

#include "pantalla.h" // inheriting class's header file
#include <SDL/SDL_ttf.h>
#include <string.h>
#include <time.h>
#include "image.h"
/*
 * No description
 */
class TTecladoPantalla : public TPantalla
{
	public:
		// class constructor
		TTecladoPantalla(SDL_Surface *);
		// class destructor
		~TTecladoPantalla();
		//bool gestionTeclado(char *textoBusqueda);
		bool gestionTeclado();
		char * getTextoBusqueda();

	private:
		// No description
		void pintarPalabraBuscar(char *, int , int , bool );
		int numLetras;
		int key_delay;
        unsigned int key_init_delay;
        TConfig *fichConf;
        TImagen *miImagen;
        TConfig *fichLang;
        char textoBusqueda[16];
};

#endif // TTecladoPantalla


