// Class automatically generated by Dev-C++ New Class wizard

#ifndef TTEXT_H
#define TTEXT_H

#include "pantalla.h" // inheriting class's header file
#include "abrir_fichero.h"
#include <SDL/SDL_ttf.h>
#include <string.h>
#include <time.h>
#include "traza.h"
#include "ttaxonomia.h"
#include "image.h"

/*
 * No description
 */
class TText : public TPantalla
{
	public:
		// class constructor
		TText(SDL_Surface *screen);
		// class destructor
		~TText();
		abrir_fichero *fichero;
		void buscar_paginas(void);
        void siguiente_linea();
        void anterior_linea();
        void reset_linea();
		void pintarTodo();
		void sustituirCarateres(char *dato);
        void desplazarPantalla();
        void msg_processing(unsigned long int posString, unsigned int tam);
        int buscarTexto (char *txtBusqueda, int inicio, int sentido);
        void buscarSiguiente();
        void buscarAnterior();
        void resetBookmarks();
        void resetBusqueda();

		struct t_lineas
		{
            int *offset;
            int n_lineas;
        }lineas;

        TImagen *miImagen;
        TConfig *fichLang;


		// No description
		void pintarPagina(bool borraPantalla);
		int posLinea;
        //bool esRetorno(char dato);
		// No description
		void eliminar_retornos(char *dato);
		// No description
		void anterior_pagina();
		// No description
		void siguiente_pagina();
		void SetretrasoDesplazamientoPantalla(int x); // sets the value of retrasoDesplazamientoPantalla
		unsigned int GetretrasoDesplazamientoPantalla(); // returns the value of retrasoDesplazamientoPantalla
		void setOrientacion(int);
		int posicionLinea (int);
		void msg_info(char *str_msg);

		struct t_bookmarks
		{
            int booklist[20]; //Array de bookmarks
            int n_bookmarks; //Numero de bookmarks
            int pos_bookmarks; //Para saber por que bookmark voy navegando
            int prev_bookmarks; //Por ahora no sirve
        }arrayBookmarks;

        bool favoritos ();
        void repaginarFavoritos (float relacion);
        void addBookmarks (t_bookmarks *structBookmark, int posBookmark);
        void AsignarBookmarks(char *);
        void setDesplazamientoSuave(bool valor);
        void pintarBarraVertical();
        void taxonomia ();
        bool definiciones();
        void marcarPalabra();
        //TTaxonomia *objTaxonomia;


	private:
		// No description
		unsigned int retrasoDesplazamientoPantalla;
		bool desplazamienoSuave;
		void desplazarLineas(SDL_Surface* screenAfter, SDL_Surface* screenBefore,int separacionLineas);
		int orientacion; //1=siguienteLinea;2=siguientePagina;-1=anteriorLinea;-2=anteriorPagina;0=sin movimiento
		int ColorBookmark;
		void favoritosPantalla(int lineaFavorito);
		void borrarBookmarks (t_bookmarks *structBookmark, int inicioOrdenacion);
		char palabraBuscar[15];
		int ultimaPosicionBuscar;
//		TMenuPrincipal *menu;
};



#endif // TTEXT_H


